"""Creación de tabla Libros

Revision ID: 62fc4df173c7
Revises: 5226ea4c2b80
Create Date: 2025-05-07 19:30:04.229810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fc4df173c7'
down_revision = '5226ea4c2b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('editorial', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.drop_table('cursos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instructor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('topico', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cursos_pkey'),
    sa.UniqueConstraint('nombre', name='cursos_nombre_key')
    )
    op.drop_table('libro')
    # ### end Alembic commands ###
